

(defun color-theme-ajt-blue-sea ()
  "Created by AJT on Sept 22 2008.  blue-sea with slight changes"
  (interactive)
  (color-theme-blue-gnus)
  (let ((color-theme-is-cumulative t))
    (color-theme-blue-erc)
    (color-theme-install
     '(color-theme-blue-sea
       ((background-color . "#101048")
		(background-mode . dark)
		(border-color . "Grey")
		(cursor-color . "Grey")
		(foreground-color . "Grey")
		(mouse-color . "Grey"))
       ((Man-overstrike-face . woman-bold-face)
		(Man-underline-face . woman-italic-face))
       (default ((t (nil))))
       (bold ((t (:bold t))))
       (bold-italic ((t (:bold t :foreground "beige"))))
       (calendar-today-face ((t (:underline t))))
       (cperl-array-face ((t (:foreground "light salmon" :bold t))))
       (cperl-hash-face ((t (:foreground "beige" :bold t :italic t))))
       (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
       (custom-button-face ((t (:foreground "gainsboro"))))
       (custom-changed-face ((t (:foreground "white" :background "blue"))))
       (custom-documentation-face ((t (:foreground "light blue"))))
       (custom-face-tag-face ((t (:underline t))))
       (custom-group-tag-face ((t (:foreground "pale turquoise" :bold t))))
       (custom-group-tag-face-1 ((t (:foreground "pale turquoise" :underline t))))
       (custom-invalid-face ((t (:foreground "yellow" :background "red"))))
       (custom-modified-face ((t (:foreground "white" :background "blue"))))
       (custom-rogue-face ((t (:foreground "pink" :background "black"))))
       (custom-saved-face ((t (:underline t))))
       (custom-set-face ((t (:foreground "blue" :background "white"))))
       (custom-state-face ((t (:foreground "light salmon"))))
       (custom-variable-button-face ((t (:bold t :underline t))))
       (custom-variable-tag-face ((t (:foreground "turquoise" :bold t))))
       (diary-face ((t (:foreground "red"))))
       (dired-face-directory ((t (:bold t :foreground "sky blue"))))
       (dired-face-permissions ((t (:foreground "aquamarine"))))
       (dired-face-flagged ((t (:foreground "tomato"))))
       (dired-face-marked ((t (:foreground "light salmon"))))
       (dired-face-executable ((t (:foreground "green yellow"))))
       (eshell-ls-archive-face ((t (:bold t :foreground "medium purple"))))
       (eshell-ls-backup-face ((t (:foreground "dim gray"))))
       (eshell-ls-clutter-face ((t (:foreground "dim gray"))))
       (eshell-ls-directory-face ((t (:bold t :foreground "medium slate blue"))))
       (eshell-ls-executable-face ((t (:bold t :foreground "aquamarine"))))
       (eshell-ls-missing-face ((t (:foreground "black"))))
       (eshell-ls-picture-face ((t (:foreground "violet"))))
       (eshell-ls-product-face ((t (:foreground "light steel blue"))))
       (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
       (eshell-ls-special-face ((t (:foreground "gold"))))
       (eshell-ls-symlink-face ((t (:foreground "white"))))
       (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
       (eshell-prompt-face ((t (:foreground "light sky blue" :bold t))))
       (excerpt ((t (:italic t))))
       (fixed ((t (:bold t))))
       (flyspell-duplicate-face ((t (:foreground "Gold3" :bold t :underline t))))
       (flyspell-incorrect-face ((t (:foreground "OrangeRed" :bold t :underline t))))
       (font-lock-builtin-face ((t (:foreground "aquamarine"))))
       (font-lock-comment-face ((t (:foreground "pale green"))))
       (font-lock-constant-face ((t (:foreground "pale green"))))
       (font-lock-doc-string-face ((t (:foreground "sky blue"))))
       (font-lock-function-name-face ((t (:bold t :foreground "aquamarine"))))
       (font-lock-keyword-face ((t (:foreground "pale turquoise" :bold t))))
       (font-lock-reference-face ((t (:foreground "pale green"))))
       (font-lock-string-face ((t (:foreground "light sky blue"))))
       (font-lock-type-face ((t (:foreground "sky blue" :bold t))))
       (font-lock-variable-name-face ((t (:foreground "turquoise" :bold t))))
       (font-lock-warning-face ((t (:foreground "Red" :bold t))))
       (fringe ((t (:background "#101048"))))
       (header-line ((t (:background "#002" :foreground "cornflower blue"))))
       (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
       (highline-face ((t (:background "DeepSkyBlue4"))))
       (holiday-face ((t (:background "pink"))))
       (info-menu-5 ((t (:underline t))))
       (info-node ((t (:bold t))))
       (info-xref ((t (:bold t :foreground "sky blue"))))
       (isearch ((t (:background "slate blue"))))
       (italic ((t (:foreground "sky blue"))))
       (makefile-space-face ((t (:background "hotpink"))))
       (menu ((t (:background "#101048" :foreground "Grey"))))
       (modeline ((t (:foreground "black" :background "slate blue"))))
       (mode-line-inactive ((t (:background "dark slate blue" :foreground "black"))))
       (modeline-buffer-id ((t (:foreground "white" :background "slate blue"))))
       (modeline-mousable ((t (:foreground "light cyan" :background "slate blue"))))
       (modeline-mousable-minor-mode ((t (:foreground "light grey" :background "slate blue"))))
       (region ((t (:background "DarkSlateBlue"))))
       (secondary-selection ((t (:background "steel blue"))))
       (show-paren-match-face ((t (:foreground "white" :background "light slate blue"))))
       (show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
       (speedbar-button-face ((t (:foreground "seashell2"))))
       (speedbar-directory-face ((t (:foreground "seashell3"))))
       (speedbar-file-face ((t (:foreground "seashell4"))))
       (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
       (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
       (speedbar-tag-face ((t (:foreground "antique white"))))
       (tool-bar ((t (:background "#101048" :foreground "Grey" :box (:line-width 1 :style released-button)))))
       (underline ((t (:underline t))))
       (widget-button-face ((t (:bold t))))
       (widget-button-pressed-face ((t (:foreground "red"))))
       (widget-documentation-face ((t (:foreground "light blue"))))
       (widget-field-face ((t (:background "RoyalBlue4" :foreground "wheat"))))
       (widget-inactive-face ((t (:foreground "dim gray"))))
       (widget-single-line-field-face ((t (:background "slate blue" :foreground "wheat"))))
       (woman-bold-face ((t (:foreground "sky blue" :bold t))))
       (woman-italic-face ((t (:foreground "deep sky blue"))))
       (woman-unknown-face ((t (:foreground "LightSalmon"))))
       (zmacs-region ((t (:background "DarkSlateBlue")))) ))))

(defun color-theme-ajt-no-bold-blue-sea ()
  "Created by AJT on Sept 22 2008.  blue-sea with slight changes"
  (interactive)
  (color-theme-blue-gnus)
  (let ((color-theme-is-cumulative t))
    (color-theme-blue-erc)
    (color-theme-install
     '(color-theme-ajt-no-bold-blue-sea
       ((background-color . "#050540")
		(background-mode . dark)
		(border-color . "Grey")
		(cursor-color . "dim gray") ; Grey
		(foreground-color . "LightGrey")
		(mouse-color . "White"))
       ((Man-overstrike-face . woman-bold-face)
		(Man-underline-face . woman-italic-face))
       (default ((t (nil))))
       (bold ((t (nil))))
       (bold-italic ((t (:foreground "beige"))))
       (calendar-today-face ((t (:underline t))))
       (cperl-array-face ((t (:foreground "light salmon"))))
       (cperl-hash-face ((t (:foreground "beige" :italic t))))
       (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
       (custom-button-face ((t (:foreground "gainsboro"))))
       (custom-changed-face ((t (:foreground "white" :background "blue"))))
       (custom-documentation-face ((t (:foreground "light blue"))))
       (custom-face-tag-face ((t (:underline t))))
       (custom-group-tag-face ((t (:foreground "pale turquoise"))))
       (custom-group-tag-face-1 ((t (:foreground "pale turquoise" :underline t))))
       (custom-invalid-face ((t (:foreground "yellow" :background "red"))))
       (custom-modified-face ((t (:foreground "white" :background "blue"))))
       (custom-rogue-face ((t (:foreground "pink" :background "black"))))
       (custom-saved-face ((t (:underline t))))
       (custom-set-face ((t (:foreground "blue" :background "white"))))
       (custom-state-face ((t (:foreground "light salmon"))))
       (custom-variable-button-face ((t (:underline t))))
       (custom-variable-tag-face ((t (:foreground "turquoise"))))
       (diary-face ((t (:foreground "red"))))
       (dired-face-directory ((t (:foreground "sky blue"))))
       (dired-face-permissions ((t (:foreground "aquamarine"))))
       (dired-face-flagged ((t (:foreground "tomato"))))
       (dired-face-marked ((t (:foreground "light salmon"))))
       (dired-face-executable ((t (:foreground "green yellow"))))

	   ; diff-mode
	   (diff-added-face ((t (:foreground "green"))))
	   (diff-removed-face ((t (:foreground "red"))))

       (eshell-ls-archive-face ((t (:foreground "medium purple"))))
       (eshell-ls-backup-face ((t (:foreground "dim gray"))))
       (eshell-ls-clutter-face ((t (:foreground "dim gray"))))
       (eshell-ls-directory-face ((t (:foreground "medium slate blue"))))
       (eshell-ls-executable-face ((t (:foreground "aquamarine"))))
       (eshell-ls-missing-face ((t (:foreground "black"))))
       (eshell-ls-picture-face ((t (:foreground "violet"))))
       (eshell-ls-product-face ((t (:foreground "light steel blue"))))
       (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
       (eshell-ls-special-face ((t (:foreground "gold"))))
       (eshell-ls-symlink-face ((t (:foreground "white"))))
       (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
       (eshell-prompt-face ((t (:foreground "light sky blue"))))

	   (ebrowse-default-face ((t (nil))))
	   (ebrowse-file-name-face ((t (nil))))
	   (ebrowse-member-attribute-face ((t (:foreground "aquamarine"))))
	   (ebrowse-member-class-face ((t (:foreground "sky blue"))))
	   (ebrowse-progress-face ((t (:background "blue"))))
	   (ebrowse-root-class-face ((t (:foreground "pale green"))))
	   (ebrowse-tree-mark-face ((t (:foreground "pale turquise"))))

       (excerpt ((t (:italic t))))
       (fixed ((t (nil))))
       (flyspell-duplicate-face ((t (:foreground "Gold3" :underline t))))
       (flyspell-incorrect-face ((t (:foreground "OrangeRed" :underline t))))
       (font-lock-builtin-face ((t (:foreground "aquamarine"))))
       (font-lock-comment-face ((t (:foreground "pale green"))))
       (font-lock-constant-face ((t (:foreground "pale green"))))
       (font-lock-doc-string-face ((t (:foreground "sky blue"))))
       (font-lock-function-name-face ((t (:foreground "aquamarine"))))
       (font-lock-keyword-face ((t (:foreground "pale turquoise"))))
       (font-lock-reference-face ((t (:foreground "pale green"))))
       (font-lock-string-face ((t (:foreground "light sky blue"))))
       (font-lock-type-face ((t (:foreground "sky blue"))))
       (font-lock-variable-name-face ((t (:foreground "turquoise"))))
       (font-lock-warning-face ((t (:foreground "Red"))))
       (fringe ((t (:background "#050540"))))
       (header-line ((t (:background "#002" :foreground "cornflower blue"))))
       (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
       (highline-face ((t (:background "DeepSkyBlue4"))))
       (holiday-face ((t (:background "pink"))))
       (info-menu-5 ((t (:underline t))))
       (info-node ((t (nil))))
       (info-xref ((t (:foreground "sky blue"))))
       (isearch ((t (:background "slate blue"))))
       (italic ((t (:foreground "sky blue"))))
       (makefile-space-face ((t (:background "hotpink"))))
       (menu ((t (:background "#050540" :foreground "Grey"))))
       (modeline ((t (:foreground "black" :background "slate blue"))))
       (mode-line-inactive ((t (:background "MidnightBlue" :foreground "black"))))
       (modeline-buffer-id ((t (:foreground "white" :background "slate blue"))))
       (modeline-mousable ((t (:foreground "light cyan" :background "slate blue"))))
       (modeline-mousable-minor-mode ((t (:foreground "light grey" :background "slate blue"))))
       (region ((t (:background "DarkSlateBlue"))))
       (secondary-selection ((t (:background "steel blue"))))
       (show-paren-match-face ((t (:foreground "white" :background "light slate blue"))))
       (show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
       (speedbar-button-face ((t (:foreground "seashell2"))))
       (speedbar-directory-face ((t (:foreground "seashell3"))))
       (speedbar-file-face ((t (:foreground "seashell4"))))
       (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
       (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
       (speedbar-tag-face ((t (:foreground "antique white"))))
       (tool-bar ((t (:background "#050540" :foreground "Grey" :box (:line-width 1 :style released-button)))))
       (underline ((t (:underline t))))
       (widget-button-face ((t (nil))))
       (widget-button-pressed-face ((t (:foreground "red"))))
       (widget-documentation-face ((t (:foreground "light blue"))))
       (widget-field-face ((t (:background "RoyalBlue4" :foreground "wheat"))))
       (widget-inactive-face ((t (:foreground "dim gray"))))
       (widget-single-line-field-face ((t (:background "slate blue" :foreground "wheat"))))
       (woman-bold-face ((t (:foreground "sky blue"))))
       (woman-italic-face ((t (:foreground "deep sky blue"))))
       (woman-unknown-face ((t (:foreground "LightSalmon"))))
       (zmacs-region ((t (:background "DarkSlateBlue"))))))))
